// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

#include<iostream>
#include<string>

using namespace std;
char diffChar(string s,string t){
      if(s.empty()){
            return t[0];
      }
      
      int freq[26]={0};

      for(int i=0;i<t.length();i++){
            freq[t[i]-'a']++;
            if(i<s.length()){
                  freq[s[i]-'a']--;
            }
      }
      char ans;
      for(int i=0;i<26;i++){
            if(freq[i]==1){
                  ans='a'+i;
            }
      }

      return ans;
}
int main(){
      string s="";
      string t="a";
      cout<<diffChar(s,t);
      return 0;
}